#!/bin/csh
#setenv EPICS_CA_ADDR_LIST "129.57.239.255 129.57.211.255 129.57.243.255 129.57.224.200"
#setenv EPICS_CA_AUTO_ADDR_LIST NO

# verbose
#/usr/local/bin/nameserver/caDirServ -d 3

# short test
#/usr/local/bin/nameserver/caDirServ -f short.txt

# normal start
/usr/local/bin/nameserver/caDirServ -s -c /usr/local/bin/nameserver

exit 0

